# Generated by Django 5.2.17 on 2026-10-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sold_by_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
