# Generated by Django 5.2.17 on 2026-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sale_sold_by_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True),
        ),
    ]
